/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/posts/{id}/modify": {
    put: operations["putMethodName"];
  };
  "/api/v1/posts/{id}/hit": {
    put: operations["increaseHit"];
  };
  "/api/v1/posts/{postId}/comments/write": {
    post: operations["write"];
  };
  "/api/v1/posts/{id}/like": {
    post: operations["doLike"];
  };
  "/api/v1/posts/write": {
    post: operations["writePost"];
  };
  "/api/v1/posts/imageUpload": {
    post: operations["uploadImage"];
  };
  "/api/v1/members": {
    post: operations["join"];
  };
  "/api/v1/members/logout": {
    post: operations["logout"];
  };
  "/api/v1/members/login": {
    post: operations["login"];
  };
  "/api/v1/posts/{id}": {
    get: operations["getOne"];
  };
  "/api/v1/posts/myList": {
    get: operations["getMyList"];
  };
  "/api/v1/posts/list": {
    get: operations["getList"];
  };
  "/api/v1/posts/getImage/{fileName}": {
    get: operations["getMethodName"];
  };
  "/api/v1/members/test": {
    get: operations["test"];
  };
  "/api/v1/posts/{id}/delete": {
    delete: operations["deletePost"];
  };
  "/api/v1/posts/{id}/cancelLike": {
    delete: operations["cancelLike"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    WriteForm: {
      title: string;
      body: string;
      published?: boolean;
    };
    JoinForm: {
      username: string;
      password: string;
      passwordConfirm: string;
      email: string;
    };
    LoginForm: {
      email: string;
      password: string;
    };
    MemberDto: {
      username?: string;
      paid?: boolean;
    };
    PostCommentDto: {
      /** Format: int64 */
      id?: number;
      username?: string;
      body?: string;
      /** Format: date-time */
      createDate?: string;
      /** Format: date-time */
      modifyDate?: string;
    };
    PostDto: {
      /** Format: int64 */
      id?: number;
      title?: string;
      body?: string;
      /** Format: date-time */
      createDate?: string;
      /** Format: date-time */
      modifyDate?: string;
      /** Format: int64 */
      hit?: number;
      member?: components["schemas"]["MemberDto"];
      /** Format: int32 */
      likes?: number;
      comments?: components["schemas"]["PostCommentDto"][];
      paid?: boolean;
      published?: boolean;
    };
    PagePostDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components["schemas"]["PostDto"][];
      /** Format: int32 */
      number?: number;
      sort?: components["schemas"]["SortObject"];
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components["schemas"]["PageableObject"];
      empty?: boolean;
    };
    PageableObject: {
      /** Format: int64 */
      offset?: number;
      sort?: components["schemas"]["SortObject"];
      paged?: boolean;
      unpaged?: boolean;
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      pageSize?: number;
    };
    SortObject: {
      empty?: boolean;
      sorted?: boolean;
      unsorted?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  putMethodName: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WriteForm"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  increaseHit: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  write: {
    parameters: {
      path: {
        postId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          [key: string]: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  doLike: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  writePost: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["WriteForm"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  uploadImage: {
    requestBody?: {
      content: {
        "application/json": {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  join: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinForm"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  logout: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginForm"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  getOne: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PostDto"];
        };
      };
    };
  };
  getMyList: {
    parameters: {
      query?: {
        page?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PagePostDto"];
        };
      };
    };
  };
  getList: {
    parameters: {
      query?: {
        page?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PagePostDto"];
        };
      };
    };
  };
  getMethodName: {
    parameters: {
      path: {
        fileName: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": string[];
        };
      };
    };
  };
  test: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": string;
        };
      };
    };
  };
  deletePost: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  cancelLike: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
}
