import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers as NextUiProviders } from "./providers";
import MediumNavbar from "@/components/MediumNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Medium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <NextUiProviders>
          <MediumNavbar />
          {children}
        </NextUiProviders>
      </body>
    </html>
  );
}
