server:
  port: 8090
spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    include:
      - secret
  threads:
    virtual:
      enabled: true
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./medium;MODE=MYSQL;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[default_batch_fetch_size]": 100
        "[format_sql]": true
        "[highlight_sql]": true
        "[use_sql_comments]": true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      settings:
        web-allow-others: true
logging:
  level:
    "[com.ll.sb231130]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.orm.jdbc.bind]": TRACE
    "[org.hibernate.orm.jdbc.extract]": TRACE
    "[org.springframework.transaction.interceptor]": TRACE
