jwt:
  expiration: 1800000
  jwtRefreshExpirationMs: 1209600000
  secret: 12345678901234567890123456789012dfaklkalkflkfkfsdofiopqiwkfkadl;
  jwtCookieName: Medium-jwt
  jwtRefreshCookieName: Medium-jwt-refresh
